# 🧠 Deep Learning Fundamentals using Loan Data

## Objective
This notebook introduces **Deep Learning concepts** using:
- A **Single-Layer Neural Network**
- A **Multi-Layer Neural Network (MLP)**

We apply them to a real **loan approval classification problem**.

Dataset:
➡️ hdfc_loan_dataset_full_enriched.csv

## 📘 What is Deep Learning?

Deep Learning is a subset of Machine Learning that uses
**Neural Networks with multiple layers** to learn complex patterns.

### Comparison
| Model | Capability |
|------|-----------|
| Linear / Logistic Regression | Linear relationships |
| Single-Layer NN | Slightly non-linear |
| Multi-Layer NN | Complex non-linear patterns |

Deep Learning is widely used in:
- Credit risk modeling
- Fraud detection
- Recommendation systems

## 🧠 Neural Network Basics

### Components:
- **Input Layer** → receives features
- **Hidden Layer(s)** → learns representations
- **Output Layer** → prediction

Each neuron performs:
Weighted Sum → Activation Function → Output

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [3]:
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv("/content/drive/MyDrive/hdfc_loan_dataset_full_enriched.csv")
df.head()

Mounted at /content/drive

,Loan_ID,Bank,Customer_Name,Gender,Married,Dependents,Education,Employment_Status,Applicant_Income,Coapplicant_Income,...,Loan_to_Annual_Income,Customer_Sentiment,Religion,State,City,PIN_Code,Aadhaar_Synthetic,Phone_Number,Email,Occupation
0,HDFC100001,HDFC Bank,Rohan Verma,Male,No,2,Graduate,Salaried,56976,0,...,11.747,Positive,Hindu,Delhi,Dwarka,857743,6.940000e+11,9068671773,rohan.verma@example.in,Farmer
1,HDFC100002,HDFC Bank,Rohan Verma,Male,No,0,Graduate,Unemployed,1856,0,...,40.381,Negative,Hindu,Punjab,Ludhiana,863836,6.330000e+11,9990772625,rohan.verma@example.in,Civil Engineer
2,HDFC100003,HDFC Bank,Aditya Nair,Female,Yes,0,Graduate,Salaried,64553,0,...,3.082,Positive,Hindu,Maharashtra,Nagpur,834796,1.660000e+11,9195085016,aditya.nair@example.in,Medical Representative
3,HDFC100004,HDFC Bank,Ananya Joshi,Male,No,0,Graduate,Salaried,88450,0,...,0.621,Negative,Hindu,Gujarat,Vadodara,438590,5.528183e+10,9179335548,ananya.joshi@example.in,Marketing Executive
4,HDFC100005,HDFC Bank,Harpreet Singh,Male,Yes,3,Graduate,Self-Employed,9539,0,...,1.736,Neutral,Sikh,West Bengal,Kolkata,495224,1.560000e+11,9795137116,harpreet.singh@example.in,Shopkeeper

In [4]:
num_features = [
    'Dependents', 'Applicant_Income', 'Coapplicant_Income',
    'Loan_Amount', 'Loan_Term_Months', 'Credit_History',
    'Age', 'CIBIL_Score', 'Annual_Household_Income',
    'Debt_to_Income_Ratio', 'Existing_EMIs',
    'Number_of_Previous_Loans', 'Default_History_Count',
    'Employment_Length_Years', 'Asset_Value',
    'Monthly_Expense', 'Loan_to_Annual_Income'
]

X = df[num_features]
y = df['Loan_Status']

In [5]:
encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)

encoder.classes_

array(['Approved', 'Rejected'], dtype=object)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## 🔹 Single-Layer Neural Network

A single-layer neural network:
- Has **no hidden layers**
- Works similarly to Logistic Regression
- Learns linear decision boundaries

Used mainly for:
- Baseline deep learning models
- Comparison with deeper networks

In [7]:
single_layer_model = Sequential([
    Dense(1, activation='sigmoid', input_shape=(X_train_scaled.shape[1],))
])

single_layer_model.compile(
    optimizer=Adam(learning_rate=0.01),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

single_layer_model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 1)              │            18 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 18 (72.00 B)

 Trainable params: 18 (72.00 B)

 Non-trainable params: 0 (0.00 B)

In [8]:
single_layer_model.fit(
    X_train_scaled, y_train,
    epochs=30,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

Epoch 1/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.6500 - loss: 0.6331 - val_accuracy: 0.7188 - val_loss: 0.5515
Epoch 2/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7797 - loss: 0.4913 - val_accuracy: 0.7937 - val_loss: 0.4621
Epoch 3/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8219 - loss: 0.4260 - val_accuracy: 0.8125 - val_loss: 0.4128
Epoch 4/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8344 - loss: 0.3873 - val_accuracy: 0.8313 - val_loss: 0.3849
Epoch 5/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8469 - loss: 0.3646 - val_accuracy: 0.8313 - val_loss: 0.3646
Epoch 6/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8500 - loss: 0.3503 - val_accuracy: 0.8313 - val_loss: 0.3536
Epoch 7/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3403 - val_accuracy: 0.8375 - val_loss: 0.3441
Epoch 8/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8547 - loss: 0.3326 - val_accuracy: 0.8313 - val_loss: 0.3387
Epoch 9/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8594 - loss: 0.3271 - val_accuracy: 0.8375 - val_loss: 0.3344
Epoch 10/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8578 - loss: 0.3232 - val_accuracy: 0.8438 - val_loss: 0.3302
Epoch 11/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8609 - loss: 0.3200 - val_accuracy: 0.8375 - val_loss: 0.3269
Epoch 12/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8578 - loss: 0.3169 - val_accuracy: 0.8438 - val_loss: 0.3253
Epoch 13/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8594 - loss: 0.3145 - val_accuracy: 0.8438 - val_loss: 0.3228
Epoch 14/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8578 - loss: 0.3126 - val_accuracy: 0.8375 - val_loss: 0.3206
Epoch 15/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8578 - loss: 0.3114 - val_accuracy: 0.8562 - val_loss: 0.3200
Epoch 16/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8594 - loss: 0.3108 - val_accuracy: 0.8562 - val_loss: 0.3202
Epoch 17/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8562 - loss: 0.3094 - val_accuracy: 0.8562 - val_loss: 0.3187
Epoch 18/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3084 - val_accuracy: 0.8562 - val_loss: 0.3177
Epoch 19/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8547 - loss: 0.3090 - val_accuracy: 0.8562 - val_loss: 0.3179
Epoch 20/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8578 - loss: 0.3078 - val_accuracy: 0.8562 - val_loss: 0.3169
Epoch 21/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8594 - loss: 0.3076 - val_accuracy: 0.8625 - val_loss: 0.3166
Epoch 22/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8609 - loss: 0.3066 - val_accuracy: 0.8562 - val_loss: 0.3181
Epoch 23/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8594 - loss: 0.3074 - val_accuracy: 0.8500 - val_loss: 0.3158
Epoch 24/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8562 - loss: 0.3061 - val_accuracy: 0.8562 - val_loss: 0.3149
Epoch 25/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8578 - loss: 0.3063 - val_accuracy: 0.8625 - val_loss: 0.3157
Epoch 26/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8562 - loss: 0.3054 - val_accuracy: 0.8687 - val_loss: 0.3161
Epoch 27/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8547 - loss: 0.3054 - val_accuracy: 0.8625 - val_loss: 0.3153
Epoch 28/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8578 - loss: 0.3050 - val_accuracy: 0.8500 - val_loss: 0.3159
Epoch 29/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8562 - loss: 0.3056 - val_accuracy: 0.8625 - val_loss: 0.3150
Epoch 30/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8578 - loss: 0.3060 - val_accuracy: 0.8625 - val_loss: 0.3147

In [9]:
single_loss, single_acc = single_layer_model.evaluate(X_test_scaled, y_test)
print("Single-Layer NN Accuracy:", single_acc)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8100 - loss: 0.4557
Single-Layer NN Accuracy: 0.8100000023841858

## 🔹 Multi-Layer Neural Network (MLP)

A Multi-Layer Perceptron:
- Has **one or more hidden layers**
- Learns complex non-linear patterns
- Forms the foundation of deep learning

This is the most common DL model for tabular data.

In [10]:
mlp_model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

mlp_model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

mlp_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 64)             │         1,152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,265 (12.75 KB)

 Trainable params: 3,265 (12.75 KB)

 Non-trainable params: 0 (0.00 B)

In [11]:
mlp_model.fit(
    X_train_scaled, y_train,
    epochs=40,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

Epoch 1/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 4s 25ms/step - accuracy: 0.7141 - loss: 0.6133 - val_accuracy: 0.7750 - val_loss: 0.5331
Epoch 2/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8062 - loss: 0.4900 - val_accuracy: 0.8375 - val_loss: 0.4531
Epoch 3/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.8375 - loss: 0.4154 - val_accuracy: 0.8562 - val_loss: 0.3914
Epoch 4/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.8594 - loss: 0.3600 - val_accuracy: 0.8562 - val_loss: 0.3515
Epoch 5/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8781 - loss: 0.3191 - val_accuracy: 0.8438 - val_loss: 0.3292
Epoch 6/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8828 - loss: 0.2903 - val_accuracy: 0.8313 - val_loss: 0.3195
Epoch 7/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8875 - loss: 0.2694 - val_accuracy: 0.8313 - val_loss: 0.3139
Epoch 8/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8953 - loss: 0.2536 - val_accuracy: 0.8438 - val_loss: 0.3174
Epoch 9/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9047 - loss: 0.2427 - val_accuracy: 0.8188 - val_loss: 0.3168
Epoch 10/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9031 - loss: 0.2336 - val_accuracy: 0.8250 - val_loss: 0.3181
Epoch 11/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9109 - loss: 0.2248 - val_accuracy: 0.8313 - val_loss: 0.3165
Epoch 12/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9109 - loss: 0.2194 - val_accuracy: 0.8313 - val_loss: 0.3212
Epoch 13/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9219 - loss: 0.2136 - val_accuracy: 0.8375 - val_loss: 0.3221
Epoch 14/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9125 - loss: 0.2063 - val_accuracy: 0.8375 - val_loss: 0.3227
Epoch 15/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9203 - loss: 0.2009 - val_accuracy: 0.8375 - val_loss: 0.3229
Epoch 16/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9187 - loss: 0.1950 - val_accuracy: 0.8313 - val_loss: 0.3291
Epoch 17/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9234 - loss: 0.1901 - val_accuracy: 0.8313 - val_loss: 0.3286
Epoch 18/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9250 - loss: 0.1853 - val_accuracy: 0.8438 - val_loss: 0.3254
Epoch 19/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9266 - loss: 0.1843 - val_accuracy: 0.8250 - val_loss: 0.3344
Epoch 20/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9281 - loss: 0.1765 - val_accuracy: 0.8313 - val_loss: 0.3351
Epoch 21/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9297 - loss: 0.1739 - val_accuracy: 0.8250 - val_loss: 0.3418
Epoch 22/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9297 - loss: 0.1695 - val_accuracy: 0.8313 - val_loss: 0.3346
Epoch 23/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9359 - loss: 0.1670 - val_accuracy: 0.8313 - val_loss: 0.3367
Epoch 24/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9391 - loss: 0.1621 - val_accuracy: 0.8250 - val_loss: 0.3421
Epoch 25/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9438 - loss: 0.1582 - val_accuracy: 0.8250 - val_loss: 0.3449
Epoch 26/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9438 - loss: 0.1539 - val_accuracy: 0.8375 - val_loss: 0.3480
Epoch 27/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9469 - loss: 0.1520 - val_accuracy: 0.8438 - val_loss: 0.3503
Epoch 28/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9422 - loss: 0.1480 - val_accuracy: 0.8375 - val_loss: 0.3500
Epoch 29/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9469 - loss: 0.1451 - val_accuracy: 0.8313 - val_loss: 0.3573
Epoch 30/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9484 - loss: 0.1412 - val_accuracy: 0.8375 - val_loss: 0.3550
Epoch 31/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9469 - loss: 0.1379 - val_accuracy: 0.8313 - val_loss: 0.3623
Epoch 32/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9531 - loss: 0.1350 - val_accuracy: 0.8438 - val_loss: 0.3652
Epoch 33/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9500 - loss: 0.1326 - val_accuracy: 0.8438 - val_loss: 0.3649
Epoch 34/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9531 - loss: 0.1303 - val_accuracy: 0.8438 - val_loss: 0.3729
Epoch 35/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9547 - loss: 0.1256 - val_accuracy: 0.8313 - val_loss: 0.3694
Epoch 36/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9547 - loss: 0.1249 - val_accuracy: 0.8375 - val_loss: 0.3798
Epoch 37/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9578 - loss: 0.1227 - val_accuracy: 0.8438 - val_loss: 0.3793
Epoch 38/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9609 - loss: 0.1192 - val_accuracy: 0.8438 - val_loss: 0.3850
Epoch 39/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9578 - loss: 0.1187 - val_accuracy: 0.8188 - val_loss: 0.3822
Epoch 40/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9609 - loss: 0.1180 - val_accuracy: 0.8250 - val_loss: 0.3867

In [12]:
mlp_loss, mlp_acc = mlp_model.evaluate(X_test_scaled, y_test)
print("Multi-Layer NN Accuracy:", mlp_acc)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8400 - loss: 0.5320
Multi-Layer NN Accuracy: 0.8399999737739563

## 📊 Model Comparison

In [13]:
pd.DataFrame({
    'Model': ['Single-Layer NN', 'Multi-Layer NN'],
    'Accuracy': [single_acc, mlp_acc]
})

             Model  Accuracy
0  Single-Layer NN      0.81
1   Multi-Layer NN      0.84

## 🏦 Business Interpretation

- Single-Layer NN ≈ Logistic Regression baseline
- Multi-Layer NN captures interactions between:
  - Income
  - Credit score
  - Debt ratio
- Better suited for complex loan approval decisions

⚠️ Deep learning requires:
- Proper scaling
- Careful tuning
- Explainability (next topic)

## 🧠 Practice Exercises

1. Increase the number of hidden layers and observe overfitting.
2. Change activation functions (ReLU → Tanh).
3. Reduce learning rate and compare convergence.
4. Compare DL accuracy with Random Forest from previous notebook.

In [14]:
deep_model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])

deep_model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history_deep = deep_model.fit(
    X_train_scaled, y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

deep_loss, deep_acc = deep_model.evaluate(X_test_scaled, y_test)
print("Deep Model Accuracy:", deep_acc)

Epoch 1/50

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 0.7141 - loss: 0.6184 - val_accuracy: 0.7937 - val_loss: 0.5293
Epoch 2/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8344 - loss: 0.4147 - val_accuracy: 0.8438 - val_loss: 0.3719
Epoch 3/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8687 - loss: 0.3106 - val_accuracy: 0.8438 - val_loss: 0.3221
Epoch 4/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8938 - loss: 0.2567 - val_accuracy: 0.8313 - val_loss: 0.3188
Epoch 5/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8953 - loss: 0.2348 - val_accuracy: 0.8250 - val_loss: 0.3193
Epoch 6/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9109 - loss: 0.2145 - val_accuracy: 0.8500 - val_loss: 0.3152
Epoch 7/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9047 - loss: 0.2048 - val_accuracy: 0.8313 - val_loss: 0.3189
Epoch 8/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9234 - loss: 0.1875 - val_accuracy: 0.8500 - val_loss: 0.3285
Epoch 9/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9266 - loss: 0.1775 - val_accuracy: 0.8562 - val_loss: 0.3391
Epoch 10/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9359 - loss: 0.1610 - val_accuracy: 0.8375 - val_loss: 0.3423
Epoch 11/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9359 - loss: 0.1517 - val_accuracy: 0.8562 - val_loss: 0.3556
Epoch 12/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9469 - loss: 0.1384 - val_accuracy: 0.8375 - val_loss: 0.3573
Epoch 13/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9563 - loss: 0.1292 - val_accuracy: 0.8313 - val_loss: 0.3657
Epoch 14/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9547 - loss: 0.1263 - val_accuracy: 0.8562 - val_loss: 0.3829
Epoch 15/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9641 - loss: 0.1094 - val_accuracy: 0.8375 - val_loss: 0.3962
Epoch 16/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9719 - loss: 0.0965 - val_accuracy: 0.8375 - val_loss: 0.4188
Epoch 17/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9766 - loss: 0.0891 - val_accuracy: 0.8313 - val_loss: 0.4391
Epoch 18/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9797 - loss: 0.0829 - val_accuracy: 0.8375 - val_loss: 0.4260
Epoch 19/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9781 - loss: 0.0813 - val_accuracy: 0.8375 - val_loss: 0.4750
Epoch 20/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9828 - loss: 0.0745 - val_accuracy: 0.8375 - val_loss: 0.4669
Epoch 21/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9875 - loss: 0.0603 - val_accuracy: 0.8375 - val_loss: 0.4838
Epoch 22/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9922 - loss: 0.0526 - val_accuracy: 0.8188 - val_loss: 0.5114
Epoch 23/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9859 - loss: 0.0516 - val_accuracy: 0.8375 - val_loss: 0.5236
Epoch 24/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9906 - loss: 0.0463 - val_accuracy: 0.8188 - val_loss: 0.5701
Epoch 25/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9953 - loss: 0.0329 - val_accuracy: 0.8188 - val_loss: 0.5570
Epoch 26/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9953 - loss: 0.0283 - val_accuracy: 0.8188 - val_loss: 0.5965
Epoch 27/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9953 - loss: 0.0289 - val_accuracy: 0.8250 - val_loss: 0.6255
Epoch 28/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9969 - loss: 0.0214 - val_accuracy: 0.8125 - val_loss: 0.6323
Epoch 29/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9969 - loss: 0.0189 - val_accuracy: 0.8250 - val_loss: 0.6636
Epoch 30/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9969 - loss: 0.0162 - val_accuracy: 0.8188 - val_loss: 0.6872
Epoch 31/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0152 - val_accuracy: 0.8250 - val_loss: 0.7018
Epoch 32/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0132 - val_accuracy: 0.8188 - val_loss: 0.7245
Epoch 33/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9984 - loss: 0.0118 - val_accuracy: 0.8188 - val_loss: 0.7417
Epoch 34/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0110 - val_accuracy: 0.8250 - val_loss: 0.7602
Epoch 35/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9984 - loss: 0.0089 - val_accuracy: 0.8125 - val_loss: 0.7779
Epoch 36/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0080 - val_accuracy: 0.8188 - val_loss: 0.7930
Epoch 37/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0068 - val_accuracy: 0.8125 - val_loss: 0.8135
Epoch 38/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9984 - loss: 0.0061 - val_accuracy: 0.8125 - val_loss: 0.8199
Epoch 39/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9984 - loss: 0.0055 - val_accuracy: 0.8188 - val_loss: 0.8426
Epoch 40/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0048 - val_accuracy: 0.8125 - val_loss: 0.8558
Epoch 41/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0043 - val_accuracy: 0.8125 - val_loss: 0.8713
Epoch 42/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9984 - loss: 0.0038 - val_accuracy: 0.8125 - val_loss: 0.8832
Epoch 43/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9984 - loss: 0.0035 - val_accuracy: 0.8125 - val_loss: 0.8958
Epoch 44/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9984 - loss: 0.0031 - val_accuracy: 0.8125 - val_loss: 0.9111
Epoch 45/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9984 - loss: 0.0029 - val_accuracy: 0.8125 - val_loss: 0.9266
Epoch 46/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9984 - loss: 0.0027 - val_accuracy: 0.8250 - val_loss: 0.9313
Epoch 47/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0025 - val_accuracy: 0.8125 - val_loss: 0.9461
Epoch 48/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0022 - val_accuracy: 0.8188 - val_loss: 0.9549
Epoch 49/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0020 - val_accuracy: 0.8250 - val_loss: 0.9676
Epoch 50/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0019 - val_accuracy: 0.8188 - val_loss: 0.9713
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7950 - loss: 1.5089
Deep Model Accuracy: 0.7950000166893005

2.Change activation functions (ReLU → Tanh)

In [15]:
tanh_model = Sequential([
    Dense(64, activation='tanh', input_shape=(X_train_scaled.shape[1],)),
    Dense(32, activation='tanh'),
    Dense(1, activation='sigmoid')
])

tanh_model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history_tanh = tanh_model.fit(
    X_train_scaled, y_train,
    epochs=30,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

tanh_loss, tanh_acc = tanh_model.evaluate(X_test_scaled, y_test)
print("Tanh Model Accuracy:", tanh_acc)

Epoch 1/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - accuracy: 0.7281 - loss: 0.5451 - val_accuracy: 0.8000 - val_loss: 0.4391
Epoch 2/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8391 - loss: 0.3841 - val_accuracy: 0.8188 - val_loss: 0.3672
Epoch 3/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8578 - loss: 0.3342 - val_accuracy: 0.8375 - val_loss: 0.3355
Epoch 4/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8641 - loss: 0.3128 - val_accuracy: 0.8313 - val_loss: 0.3263
Epoch 5/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8625 - loss: 0.3039 - val_accuracy: 0.8500 - val_loss: 0.3178
Epoch 6/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8656 - loss: 0.2970 - val_accuracy: 0.8500 - val_loss: 0.3180
Epoch 7/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8625 - loss: 0.2944 - val_accuracy: 0.8500 - val_loss: 0.3145
Epoch 8/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8641 - loss: 0.2911 - val_accuracy: 0.8500 - val_loss: 0.3188
Epoch 9/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8656 - loss: 0.2876 - val_accuracy: 0.8562 - val_loss: 0.3148
Epoch 10/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8687 - loss: 0.2873 - val_accuracy: 0.8500 - val_loss: 0.3174
Epoch 11/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8656 - loss: 0.2821 - val_accuracy: 0.8438 - val_loss: 0.3126
Epoch 12/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8703 - loss: 0.2814 - val_accuracy: 0.8500 - val_loss: 0.3134
Epoch 13/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8750 - loss: 0.2751 - val_accuracy: 0.8562 - val_loss: 0.3184
Epoch 14/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8734 - loss: 0.2737 - val_accuracy: 0.8500 - val_loss: 0.3137
Epoch 15/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8859 - loss: 0.2700 - val_accuracy: 0.8500 - val_loss: 0.3119
Epoch 16/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8844 - loss: 0.2680 - val_accuracy: 0.8438 - val_loss: 0.3147
Epoch 17/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8844 - loss: 0.2667 - val_accuracy: 0.8375 - val_loss: 0.3147
Epoch 18/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8922 - loss: 0.2642 - val_accuracy: 0.8438 - val_loss: 0.3124
Epoch 19/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8891 - loss: 0.2576 - val_accuracy: 0.8313 - val_loss: 0.3115
Epoch 20/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8891 - loss: 0.2528 - val_accuracy: 0.8313 - val_loss: 0.3131
Epoch 21/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8984 - loss: 0.2495 - val_accuracy: 0.8313 - val_loss: 0.3142
Epoch 22/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8922 - loss: 0.2481 - val_accuracy: 0.8375 - val_loss: 0.3130
Epoch 23/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8984 - loss: 0.2407 - val_accuracy: 0.8375 - val_loss: 0.3113
Epoch 24/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9047 - loss: 0.2396 - val_accuracy: 0.8438 - val_loss: 0.3129
Epoch 25/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8969 - loss: 0.2367 - val_accuracy: 0.8375 - val_loss: 0.3150
Epoch 26/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9078 - loss: 0.2329 - val_accuracy: 0.8313 - val_loss: 0.3154
Epoch 27/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9031 - loss: 0.2303 - val_accuracy: 0.8438 - val_loss: 0.3177
Epoch 28/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9094 - loss: 0.2265 - val_accuracy: 0.8375 - val_loss: 0.3161
Epoch 29/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9109 - loss: 0.2233 - val_accuracy: 0.8500 - val_loss: 0.3170
Epoch 30/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9172 - loss: 0.2177 - val_accuracy: 0.8375 - val_loss: 0.3217
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8200 - loss: 0.4329
Tanh Model Accuracy: 0.8199999928474426

3.Reduce learning rate and compare convergence.

In [17]:
slow_lr_model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

slow_lr_model.compile(
    optimizer=Adam(learning_rate=0.0001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history_slow = slow_lr_model.fit(
    X_train_scaled, y_train,
    epochs=30,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

slow_loss, slow_acc = slow_lr_model.evaluate(X_test_scaled, y_test)
print("Reduced LR Accuracy:", slow_acc)

Epoch 1/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.6109 - loss: 0.6612 - val_accuracy: 0.6187 - val_loss: 0.6573
Epoch 2/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6719 - loss: 0.6402 - val_accuracy: 0.6875 - val_loss: 0.6405
Epoch 3/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7063 - loss: 0.6213 - val_accuracy: 0.7188 - val_loss: 0.6251
Epoch 4/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7328 - loss: 0.6044 - val_accuracy: 0.7563 - val_loss: 0.6108
Epoch 5/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7484 - loss: 0.5882 - val_accuracy: 0.7688 - val_loss: 0.5975
Epoch 6/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7672 - loss: 0.5736 - val_accuracy: 0.7625 - val_loss: 0.5843
Epoch 7/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7797 - loss: 0.5591 - val_accuracy: 0.7688 - val_loss: 0.5720
Epoch 8/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7875 - loss: 0.5456 - val_accuracy: 0.7625 - val_loss: 0.5600
Epoch 9/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7969 - loss: 0.5326 - val_accuracy: 0.7750 - val_loss: 0.5482
Epoch 10/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8094 - loss: 0.5200 - val_accuracy: 0.7750 - val_loss: 0.5366
Epoch 11/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8156 - loss: 0.5079 - val_accuracy: 0.7875 - val_loss: 0.5255
Epoch 12/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8234 - loss: 0.4963 - val_accuracy: 0.8000 - val_loss: 0.5145
Epoch 13/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8250 - loss: 0.4851 - val_accuracy: 0.8062 - val_loss: 0.5037
Epoch 14/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8250 - loss: 0.4742 - val_accuracy: 0.8000 - val_loss: 0.4936
Epoch 15/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8297 - loss: 0.4638 - val_accuracy: 0.8062 - val_loss: 0.4837
Epoch 16/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8297 - loss: 0.4540 - val_accuracy: 0.8188 - val_loss: 0.4746
Epoch 17/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8375 - loss: 0.4446 - val_accuracy: 0.8250 - val_loss: 0.4652
Epoch 18/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8375 - loss: 0.4355 - val_accuracy: 0.8313 - val_loss: 0.4567
Epoch 19/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8422 - loss: 0.4269 - val_accuracy: 0.8250 - val_loss: 0.4479
Epoch 20/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8391 - loss: 0.4185 - val_accuracy: 0.8313 - val_loss: 0.4398
Epoch 21/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8422 - loss: 0.4105 - val_accuracy: 0.8313 - val_loss: 0.4323
Epoch 22/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8484 - loss: 0.4029 - val_accuracy: 0.8375 - val_loss: 0.4254
Epoch 23/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8484 - loss: 0.3958 - val_accuracy: 0.8438 - val_loss: 0.4182
Epoch 24/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8547 - loss: 0.3888 - val_accuracy: 0.8438 - val_loss: 0.4117
Epoch 25/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8594 - loss: 0.3825 - val_accuracy: 0.8500 - val_loss: 0.4050
Epoch 26/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8594 - loss: 0.3760 - val_accuracy: 0.8500 - val_loss: 0.3994
Epoch 27/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8578 - loss: 0.3699 - val_accuracy: 0.8500 - val_loss: 0.3940
Epoch 28/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8625 - loss: 0.3644 - val_accuracy: 0.8500 - val_loss: 0.3888
Epoch 29/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8625 - loss: 0.3588 - val_accuracy: 0.8438 - val_loss: 0.3838
Epoch 30/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8609 - loss: 0.3537 - val_accuracy: 0.8500 - val_loss: 0.3791
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7750 - loss: 0.4696
Reduced LR Accuracy: 0.7749999761581421

4.Compare DL accuracy with Random Forest from previous notebook.

In [18]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

rf_model.fit(X_train_scaled, y_train)

rf_pred = rf_model.predict(X_test_scaled)

rf_acc = accuracy_score(y_test, rf_pred)

print("Random Forest Accuracy:", rf_acc)

Random Forest Accuracy: 0.84

In [19]:
import pandas as pd

pd.DataFrame({
    'Model': [
        'Single Layer',
        'MLP',
        'Deep Model',
        'Tanh Model',
        'Reduced LR Model',
        'Random Forest'
    ],
    'Accuracy': [
        single_acc,
        mlp_acc,
        deep_acc,
        tanh_acc,
        slow_acc,
        rf_acc
    ]
})

              Model  Accuracy
0      Single Layer     0.810
1               MLP     0.840
2        Deep Model     0.795
3        Tanh Model     0.820
4  Reduced LR Model     0.775
5     Random Forest     0.840